name: Build and Push To Full Build branch
on: 
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    name: Build and Push To Full Build branch 
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    if: github.repository_owner == 'Ruby-Network'
    steps:
      - name: Checkout (full build)
        uses: actions/checkout@v3
      - name: Submodule Update
        run: git submodule update --init --recursive
      - name: Switch to full build branch and merge
        run: |
          git checkout -b full-build
          git merge main
      - name: Setup Node 
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Setup Ruby 
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
      - name: Install other things
        run: sudo apt update && sudo apt install -y build-essential libpq-dev
      - name: Install PNPM
        run: npm install -g pnpm 
      - name: Install 
        run: pnpm install 
      - name: Build 
        run: |
          pnpm run build 
          make
      - name: Commit to branch 
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Build from Github Actions"
          git push --set-upstream origin full-build --force
