name: Build and Push To Full Build branch
on: 
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    name: Build and Push To Full Build branch 
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    if: github.repository_owner == 'Ruby-Network'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: full-build
      - name: Submodule Update
        run: git submodule update --init --recursive
      - name: Setup Node 
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Setup Ruby 
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
      - name: Install other things
        run: sudo apt update && sudo apt install -y build-essential libpq-dev
      - name: Install PNPM
        run: npm install -g pnpm 
      - name: Install 
        run: pnpm install 
      - name: Build 
        run: |
          pnpm run build 
          make
      - name: Commit to branch 
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Build"
          git push origin full-build
