# depend on both the ./dockerHub.yml and ./docker-build.yml workflows to complete before running the update.yml workflow.
name: Update server
on:
  workflow_run:
    workflows: ["Docker Build (Docker Hub)", "Docker Build"]
    types:
      - completed
  workflow_dispatch:

jobs:
  # Git clone our ansible-scripts repository (private)
  git-clone-ansible-scripts:
    name: Git Clone Ansible Scripts
    runs-on: ubuntu-latest
    steps:
      - name: Git Clone our Private Ansible Scripts
        uses: actions/checkout@v3
        with:
          repository: Ruby-Network/ansible-scripts
          token: ${{ secrets.GH_TOKEN }}
          ref: main
      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install ansible -y
